const i18nMapping = {
	[DEFAULT_LOCALE]: {
		"sign-in-form-header": "Sign In",
		"sign-out-form-header": "Sign Out",
		"user-data-reset-label": "Reset Settings",
		"sign-in-form-email-nickname-label": "Email or Nickname",
		"sign-in-form-password-label": "Password",
		"sign-up-form-header": "Sign Up",
		"sign-up-form-phone-number-label": "Phone Number *",
		"sign-up-form-email-label": "Email *",
		"sign-up-form-dob-label": "Date of Birth *",
		"sign-up-form-password-label": "Password *",
		"sign-up-form-suggest-password-label": "Suggest Password",
		"sign-up-form-show-password-label": "Show",
		"sign-up-form-hide-password-label": "Hide",
		"sign-up-form-first-name-label": "First Name *",
		"sign-up-form-last-name-label": "Last Name *",
		"sign-up-form-patronymic-label": "Patronymic",
		"sign-up-form-nickname-label": "Nickname *",
		"sign-up-form-new-nickname-label": "New Nickname",
		"sign-up-form-agree-with-label": "Agree with ",
		"sign-up-form-tos-label": "Terms of Service",
		"request-demo-form-header": "Request Demo",
		"request-demo-form-products-label": "Zendesk Products *",
		"request-demo-form-search-label": "Search:",
		"request-demo-form-filter-label": "Filter:",
		"request-demo-form-reset-filter-label": "Reset Filter",
		"request-demo-form-name-label": "Your Name *",
		"request-demo-form-email-label": "Contact Email *",
		"request-demo-form-date-label": "Suitable Date *",
		"request-demo-form-time-label": "Suitable Time *",
		"request-demo-form-save-label": "Save",
		"request-demo-summary-header": "Request Demo Summary",
		"request-demo-summary-products-label": "Selected Zendesk Products",
		"request-demo-summary-contact-header": "Contact Info",
		"request-demo-summary-name-label": "Name",
		"request-demo-summary-email-label": "Email",
		"request-demo-summary-timestamp-header": "Selected Timestamp",
		"request-demo-summary-timestamp-preposition": "at",
		"request-demo-summary-confirm-label": "Confirm",
		"request-demo-summary-cancel-label": "Cancel",
		"admin-panel-header": "Admin Panel",
		"admin-panel-users-header": "Users",
		"admin-panel-row-number-label": "#",
		"admin-panel-phone-number-label": "Phone Number",
		"admin-panel-email-label": "Email",
		"admin-panel-dob-label": "Date of Birth",
		"admin-panel-first-name-label": "First Name",
		"admin-panel-last-name-label": "Last Name",
		"admin-panel-patronymic-label": "Patronymic",
		"admin-panel-nickname-label": "Nickname",
		"admin-panel-demo-requests-label": "Demo Requests",
		"header-product-support-label": "Product Support",
		"header-company-label": "Company",
		"header-contact-us-label": "Contact us",
		"header-language-label": "English",
		"header-products-label": "Products",
		"header-messaging-live-chat-label": "Messaging and Live Chat",
		"header-privacy-protection-label": "Data Privacy and Protection",
		"header-help-center-label": "Help Center",
		"header-pricing-label": "Pricing",
		"header-for-service-label": "For Service",
		"header-for-sales-label": "For Sales",
		"header-solutions-label": "Solutions",
		"header-enterprise-label": "Enterprise",
		"header-industries-label": "Industries",
		"header-demo-label": "Demo",
		"header-watch-demo-label": "Watch Demo",
		"header-start-trial-label": "Start Trial",
		"header-services-label": "Services",
		"header-ticketing-system-label": "Ticketing System",
		"header-forum-software-label": "Forum Software",
		"header-resources-label": "Resources",
		"header-blog-label": "Blog",
		"header-cx-trends-label": "Customer Experience Trends",
		"header-get-started-label": "Get started",
		"page-content-play-pause-label": "Play/Pause",
		"page-content-champions-text": "Champions",
		"page-content-customer-service-preposition": "of",
		"page-content-customer-text": "customer",
		"page-content-service-text": "service",
		"page-content-customer-service-trial-text": "Zendesk makes customer service better. We build software to meet customer needs, set your team up for success, and keep your business in sync.",
		"page-content-free-trial-label": "Free trial",
		"page-content-view-demo-label": "View demo",
		"page-content-messaging-description-header-text": "Go all in on messaging",
		"page-content-messaging-description-main-text": "Cue the confetti—Zendesk messaging is here to help deliver rich conversational experiences that are connected across your web, mobile and social apps. It’s easy to automate and fast to scale for every customer need—and it’s all part of our new Zendesk Suite.",
		"page-content-watch-video-label": "Watch video",
		"page-content-get-details-label": "Get the details",
		"page-content-customer-support-header-text": "Where good conversations become great experiences",
		"page-content-customer-support-header-additional-text": "To make customers happy, you need conversational experiences—connected communication across any channel.",
		"page-content-service-label": "Service",
		"page-content-sales-label": "Sales",
		"page-content-customer-support-header-text": "Give customers the best support",
		"page-content-customer-support-additional-text": "Customers want to connect any time, any place. Meet them where they are with the Zendesk Suite, which provides sophisticated, seamless support that flows across channels.",
		"page-content-learn-more-label": "Learn more",
		"page-content-squarespace-quote-text": "We’re here to help our customers succeed online, and that’s something we hear back from our customers. They just love our support channels.",
		"page-content-squarespace-quote-author-text": "Raphael Fontes",
		"page-content-squarespace-quote-author-title-text": "Vice President of Customer Operations at Squarespace",
		"page-content-cx-header-text": "Customize your customer experience",
		"page-content-cx-additional-text": "Glowing just under the surface of Zendesk is a powerful force that lets you connect and understand all of your customer data. Plus, it’s flexible and customizable, so you can adapt to anything thrown your way. Zendesk Sunshine isn’t faster than a speeding bullet, but it’s close.",
		"page-content-cx-trends-card-header": "CX Trends 2021",
		"page-content-new-cx-header": "New world, new CX",
		"page-content-cx-trends-description-text": "Last year, customer needs changed in a blink. Learn how your team can keep up.",
		"page-content-read-report-label": "Read report",
		"page-content-cx-champions-card-header": "CX Champions",
		"page-content-cx-champions-header-text": "Speed + quality = agility",
		"page-content-cx-champions-description": "How leading CX orgs support customer-centric processes and drive business agility.",
		"page-content-read-more-label": "Read more",
		"page-content-new-product-card-header": "New product offering",
		"page-content-new-product-header-text": "Introducing the Zendesk Suite",
		"page-content-new-product-description": "Our new all-in-one customer service solution is easy to use, convenient for customers, and scales with your business.",
		"page-content-digital-customer-service-text": "#1 in Digital Customer Service use case by",
		"page-content-customer-stories-header": "The best customer experiences are built with Zendesk",
		"page-content-customer-stories-additional-text": "The companies you use, use Zendesk",
		"page-content-see-all-label": "See all customer stories",
		"page-content-cx-links-header": "There’s more where that came from",
		"page-content-cx-links-guide-text": "The complete guide to understanding customer service",
		"page-content-cx-links-update-text": "Zendesk update: staying safe and working for you",
		"page-content-cx-links-metrics-text": "3 customer service metrics that matter",
		"page-content-cx-links-objectives-text": "Most important customer service objectives",
		"page-content-cx-links-ml-text": "Understanding machine learning vs deep learning",
		"page-content-cx-links-remote-text": "Transitioning to a remote workforce",
		"page-content-cx-links-covid-text": "The impact of COVID-19 on CX",
		"page-content-cx-links-examples-text": "5 of the best knowledge management examples",
		"page-content-trials-header-text": "Champions of awesome free trials",
		"page-content-start-trial-label": "Start a free trial",
		"page-content-map-header-text": "Find Us On The Map",
		"footer-header-text": "Champions of customer service",
		"footer-products-text": "Our Products",
		"footer-zendesk-service-text": "Zendesk for service",
		"footer-zendesk-sales-text": "Zendesk for sales",
		"footer-api-text": "Platform and APIs",
		"footer-marketplace-text": "Marketplace",
		"footer-updates-text": "Product updates",
		"footer-top-features-text": "Top Features",
		"footer-voice-text": "Voice",
		"footer-community-forums-text": "Community forums",
		"footer-reporting-text": "Reporting & analytics",
		"footer-answer-bot-text": "Answer Bot",
		"footer-customer-service-text": "Customer service software",
		"footer-ticketing-system-text": "Ticketing system software",
		"footer-live-chat-text": "Live chat software",
		"footer-kb-text": "Knowledge base",
		"footer-forum-text": "Forum software",
		"footer-help-desk-text": "Help desk software",
		"footer-security-text": "Security",
		"footer-request-demo-text": "Request a demo",
		"footer-library-text": "The Library",
		"footer-training-text": "Training",
		"footer-partners-text": "Partners",
		"footer-webinars-text": "Webinars",
		"footer-customer-stories-text": "Customer Stories",
		"footer-about-us-text": "About us",
		"footer-press-text": "Press",
		"footer-investors-text": "Investors",
		"footer-events-text": "Events",
		"footer-careers-text": "Careers",
		"footer-diversity-text": "Diversity & Inclusion",
		"footer-social-impact-text": "Social Impact",
		"footer-sitemap-text": "Sitemap",
		"footer-system-status-text": "System status",
		"footer-product-help-text": "Product help",
		"footer-legal-text": "Legal",
		"footer-favorite-things-text": "Favorite Things",
		"footer-zendesk-enterprise-text": "Zendesk for Enterprise",
		"footer-zendesk-small-business-text": "Zendesk for Small Business",
		"footer-zendesk-startups-text": "Zendesk for Startups",
		"footer-zendesk-benchmark-text": "Zendesk Benchmark",
		"footer-crm-text": "Gartner CRM Magic Quadrant",
		"footer-subscribe-header-text": "Enter the fold",
		"footer-subscribe-additional-text": "Subscribe to our newsletter.",
		"footer-subscribe-label": "Subscribe",
		"footer-tou-text": "Terms of Use",
		"footer-privacy-text": "Privacy Policy",
		"footer-cookie-text": "Cookie Policy",
		"copyright-info-text": "Gartner, Critical Capabilities for the CRM Customer Engagement Center, 8 June 2020, Nadine LeBlanc, Brian Manusama",
		"copyright-description-text": "Gartner does not endorse any vendor, product or service depicted in its research publications and does not advise technology users to select only those vendors with the highest ratings or other designations. Gartner research publications consist of the opinions of Gartner's Research & Advisory organization and should not be construed as statements of fact. Gartner disclaims all warranties, expressed or implied, with respect to this research, including any warranties of merchantability or fitness for particular purpose. GARTNER is a registered trademark and service mark of Gartner, Inc. and/or its affiliates in the U.S. and internationally and is used herein with permissions. All rights reserved.",
		"category-software": "Software",
		"category-support": "Support",
		"category-cx": "Customer Experience",
		"request-demo-select-product-error": "Select at least one product",
		"request-demo-name-empty-error": "Provide contact name",
		"request-demo-name-too-short-error": "Name should be at least",
		"request-demo-name-invalid-error": "Name should be a valid name starting with capital letter",
		"error-characters": "characters long",
		"request-demo-email-empty-error": "Provide contact email",
		"request-demo-email-invalid": "Entered value should be a valid email address",
		"request-demo-date-empty-error": "Select suitable date for demo",
		"request-demo-date-out-of-range-error": "Select any suitable date from tomorrow till the end of the year",
		"request-demo-time-empty-error": "Select suitable time for demo",
		"request-demo-time-out-of-range-error": "Select any suitable time from",
		"request-demo-time-error-preposition": "till",
		"sign-in-credentials-error": "Invalid username or password",
		"sign-up-password-compromised-error": "Password is compromised",
		"sign-up-password-confirmation-error": "Passwords should match",
		"sign-up-nickname-taken-error": "This nickname is already taken",
		"sign-up-phone-empty-error": "Phone number is required",
		"sign-up-phone-invalid-error": "Entered value should be numeric",
		"sign-up-phone-too-short-error": "Phone number should be exactly",
		"sign-up-phone-too-short-error-suffix": "characters long; you entered",
		"sign-up-email-empty-error": "Email is required",
		"sign-up-dob-empty-error": "Date of Birth is required",
		"sign-up-dob-range-overflow-error": "User must be at the age of",
		"sign-up-dob-range-overflow-error-suffix": "or older",
		"sign-up-first-name-empty-error": "First Name is required",
		"sign-up-first-name-too-short-error": "First Name should be at least",
		"sign-up-first-name-invalid-error": "First Name should be a valid name starting with capital letter",
		"sign-up-last-name-empty-error": "Last Name is required",
		"sign-up-last-name-too-short-error": "First Name should be at least",
		"sign-up-last-name-invalid-error": "Last Name should be a valid surname starting with capital letter",
		"sign-up-patronymic-too-short-error": "Patronymic should be at least",
		"sign-up-patronymic-invalid-error": "Patronymic should be a valid father's name starting with capital letter",
		"sign-up-password-empty-error": "Password is required",
		"sign-up-password-too-short-error": "Password should be at least",
		"sign-up-password-too-long-error": "Password should be at most",
		"sign-up-password-weak-error": "Password should contain at least one upper case letter, one lower case letter, special symbol and a digit",
		"sign-up-nickname-too-short-error": "Nickname should be at least",
		"sign-up-nickname-empty-error": "Nickname is required",
		"sign-up-tos-missing-error": "You must agree with the Terms of Service to proceed",
		"sign-in-username-empty-error": "Email or Nickname is required",
		"footer-subscribe-email-placeholder": "Whats youre email?"
	},
	[LOCALE_RU]: {
		"sign-in-form-header": "Войти",
		"sign-out-form-header": "Выйти",
		"user-data-reset-label": "Сбросить настройки",
		"sign-in-form-email-nickname-label": "Email или Никнейм",
		"sign-in-form-password-label": "Пароль",
		"sign-up-form-header": "Зарегистрироваться",
		"sign-up-form-phone-number-label": "Номер телефона *",
		"sign-up-form-email-label": "Email *",
		"sign-up-form-dob-label": "Дата рождения *",
		"sign-up-form-password-label": "Пароль *",
		"sign-up-form-suggest-password-label": "Сгенерировать пароль",
		"sign-up-form-show-password-label": "Показать",
		"sign-up-form-hide-password-label": "Скрыть",
		"sign-up-form-first-name-label": "Имя *",
		"sign-up-form-last-name-label": "Фамилия *",
		"sign-up-form-patronymic-label": "Отчество",
		"sign-up-form-nickname-label": "Никнейм *",
		"sign-up-form-new-nickname-label": "Новый никнейм",
		"sign-up-form-agree-with-label": "Соглашаюсь с ",
		"sign-up-form-tos-label": "Условиями использования",
		"request-demo-form-header": "Подать заявку на демо",
		"request-demo-form-products-label": "Продукты Zendesk *",
		"request-demo-form-search-label": "Поиск:",
		"request-demo-form-filter-label": "Фильтр:",
		"request-demo-form-reset-filter-label": "Сбросить фильтр",
		"request-demo-form-name-label": "Ваше имя *",
		"request-demo-form-email-label": "Контактный email *",
		"request-demo-form-date-label": "Подходящая дата *",
		"request-demo-form-time-label": "Подходящее время *",
		"request-demo-form-save-label": "Сохранить",
		"request-demo-summary-header": "Итоговый запрос на демо",
		"request-demo-summary-products-label": "Выбранные продукты Zendesk",
		"request-demo-summary-contact-header": "Контактные данные",
		"request-demo-summary-name-label": "Имя",
		"request-demo-summary-email-label": "Email",
		"request-demo-summary-timestamp-header": "Выбранное время",
		"request-demo-summary-timestamp-preposition": "в",
		"request-demo-summary-confirm-label": "Подтвердить",
		"request-demo-summary-cancel-label": "Отмена",
		"admin-panel-header": "Панель администратора",
		"admin-panel-users-header": "Пользователи",
		"admin-panel-row-number-label": "№",
		"admin-panel-phone-number-label": "Номер телефона",
		"admin-panel-email-label": "Email",
		"admin-panel-dob-label": "Дата рождения",
		"admin-panel-first-name-label": "Имя",
		"admin-panel-last-name-label": "Фамилия",
		"admin-panel-patronymic-label": "Отчество",
		"admin-panel-nickname-label": "Никнейм",
		"admin-panel-demo-requests-label": "Запросы на демо",
		"header-product-support-label": "Поддержка продукта",
		"header-company-label": "Компания",
		"header-contact-us-label": "Связаться с нами",
		"header-language-label": "Русский",
		"header-products-label": "Продукты",
		"header-messaging-live-chat-label": "Рассылка сообщений и онлайн-консультация",
		"header-privacy-protection-label": "Конфиденциальность данных и защита",
		"header-help-center-label": "Справочный центр",
		"header-pricing-label": "Цены",
		"header-for-service-label": "Для обслуживания",
		"header-for-sales-label": "Для продаж",
		"header-solutions-label": "Решения",
		"header-enterprise-label": "Предприятия",
		"header-industries-label": "Промышленность",
		"header-demo-label": "Демо",
		"header-watch-demo-label": "Посмотреть демо",
		"header-start-trial-label": "Начать пробный период",
		"header-services-label": "Сервисы",
		"header-ticketing-system-label": "Система регистрации обращений",
		"header-forum-software-label": "ПО для форумов",
		"header-resources-label": "Ресурсы",
		"header-blog-label": "Блог",
		"header-cx-trends-label": "Направления в обслуживании клиентов",
		"header-get-started-label": "Начать",
		"page-content-play-pause-label": "Воспроизвести/Приостановить",
		"page-content-champions-text": "Чемпионы",
		"page-content-customer-service-preposition": "по",
		"page-content-customer-text": "обслуживанию",
		"page-content-service-text": "клиентов",
		"page-content-customer-service-trial-text": "Zendesk улучшает обслуживание клиентов. Мы создаем программное обеспечение, отвечающее потребностям клиентов, настраиваем вашу команду на успех и синхронизируем ваш бизнес.",
		"page-content-free-trial-label": "Бесплатный пробный период",
		"page-content-view-demo-label": "Посмотреть демо",
		"page-content-messaging-description-header-text": "Полностью посвятите себя обмену сообщениями",
		"page-content-messaging-description-main-text": "А теперь конфетти! — система обмена сообщениями Zendesk призвана помочь обеспечить богатые возможности общения, связанные с вашими веб-приложениями, мобильными приложениями и социальными приложениями. Его легко автоматизировать и быстро масштабировать для удовлетворения любых потребностей клиентов — и все это является частью нашего нового Zendesk Suite.",
		"page-content-watch-video-label": "Посмотреть видео",
		"page-content-get-details-label": "Получить детали",
		"page-content-customer-support-header-text": "Место, где хорошие разговоры становятся отличным опытом",
		"page-content-customer-support-header-additional-text": "Чтобы сделать клиентов счастливыми, вам нужен диалоговый опыт — связанное общение по любому каналу.",
		"page-content-service-label": "Сервис",
		"page-content-sales-label": "Продажи",
		"page-content-customer-support-header-text": "Предоставляйте клиентам лучшую поддержку",
		"page-content-customer-support-additional-text": "Клиенты хотят подключаться в любое время и в любом месте. Встретьтесь с ними там, где они есть, с помощью Zendesk Suite, который обеспечивает комплексную и бесперебойную поддержку, распространяющуюся по нескольким каналам.",
		"page-content-learn-more-label": "Узнать больше",
		"page-content-squarespace-quote-text": "Мы здесь, чтобы помочь нашим клиентам добиться успеха в Интернете, и это то, что мы слышим от наших клиентов. Им просто нравятся наши каналы поддержки.",
		"page-content-squarespace-quote-author-text": "Рафаэль Фонтес",
		"page-content-squarespace-quote-author-title-text": "Вице-президент по работе с клиентами Squarespace",
		"page-content-cx-header-text": "Настройте свой клиентский опыт",
		"page-content-cx-additional-text": "Под поверхностью Zendesk скрывается мощная сила, которая позволяет вам объединять и понимать все данные ваших клиентов. Кроме того, он гибкий и настраиваемый, поэтому вы можете адаптироваться ко всему, что встретится вам на пути. Zendesk Sunshine не быстрее пули, но близок к этому.",
		"page-content-cx-trends-card-header": "Направления CX 2021",
		"page-content-new-cx-header": "Новый мир, новый CX",
		"page-content-cx-trends-description-text": "В прошлом году потребности клиентов изменились в мгновение ока. Узнайте, как ваша команда может идти в ногу со временем.",
		"page-content-read-report-label": "Прочитать отчёт",
		"page-content-cx-champions-card-header": "Чемпионы CX",
		"page-content-cx-champions-header-text": "Скорость + качество = адаптивность",
		"page-content-cx-champions-description": "Как ведущие CX-организации поддерживают клиентоориентированные процессы и повышают гибкость бизнеса.",
		"page-content-read-more-label": "Читать далее",
		"page-content-new-product-card-header": "Предложение нового продукта",
		"page-content-new-product-header-text": "Представляем Zendesk Suite",
		"page-content-new-product-description": "Наше новое комплексное решение для обслуживания клиентов просто в использовании, удобно для клиентов и масштабируется вместе с вашим бизнесом.",
		"page-content-digital-customer-service-text": "№1 в сценарии использования цифрового обслуживания клиентов по версии",
		"page-content-customer-stories-header": "Лучшее качество обслуживания клиентов создается с помощью Zendesk",
		"page-content-customer-stories-additional-text": "Компании, которыми вы пользуетесь, используют Zendesk",
		"page-content-see-all-label": "Посмотреть все истории клиентов",
		"page-content-cx-links-header": "Это ещё не всё",
		"page-content-cx-links-guide-text": "Полное руководство по пониманию обслуживания клиентов",
		"page-content-cx-links-update-text": "Обновление Zendesk: остаёмся в безопасности и работаем для вас",
		"page-content-cx-links-metrics-text": "3 метрики обслуживания клиентов, которые имеют значение",
		"page-content-cx-links-objectives-text": "Наиболее важные цели обслуживания клиентов",
		"page-content-cx-links-ml-text": "Понимание машинного обучения по сравнению с глубоким обучением",
		"page-content-cx-links-remote-text": "Переход на удаленную работу",
		"page-content-cx-links-covid-text": "Влияние COVID-19 на CX",
		"page-content-cx-links-examples-text": "5 лучших примеров управления знаниями",
		"page-content-trials-header-text": "Чемпионы потрясающих бесплатных пробных версий",
		"page-content-start-trial-label": "Начать пробный период",
		"page-content-map-header-text": "Найти нас на карте",
		"footer-header-text": "Чемпионы по обслуживанию клиентов",
		"footer-products-text": "Наши продукты",
		"footer-zendesk-service-text": "Zendesk для обслуживания",
		"footer-zendesk-sales-text": "Zendesk для продаж",
		"footer-api-text": "Платформа и API",
		"footer-marketplace-text": "Торговая площадка",
		"footer-updates-text": "Обновления продуктов",
		"footer-top-features-text": "Основные характеристики",
		"footer-voice-text": "Голосовая связь",
		"footer-community-forums-text": "Форумы сообщества",
		"footer-reporting-text": "Отчетность и аналитика",
		"footer-answer-bot-text": "Бот для ответа на вопросы",
		"footer-customer-service-text": "ПО для обслуживания клиентов",
		"footer-ticketing-system-text": "ПО системы регистрации обращений",
		"footer-live-chat-text": "ПО для онлайн-консультаций",
		"footer-kb-text": "База знаний",
		"footer-forum-text": "ПО для форумов",
		"footer-help-desk-text": "ПО службы поддержки",
		"footer-security-text": "Безопасность",
		"footer-request-demo-text": "Оставить заявку на демо",
		"footer-library-text": "Библиотека",
		"footer-training-text": "Обучение",
		"footer-partners-text": "Партнёры",
		"footer-webinars-text": "Вебинары",
		"footer-customer-stories-text": "Истории клиентов",
		"footer-about-us-text": "О нас",
		"footer-press-text": "Пресса",
		"footer-investors-text": "Инвесторы",
		"footer-events-text": "События",
		"footer-careers-text": "Вакансии",
		"footer-diversity-text": "Разнообразие и инклюзивность",
		"footer-social-impact-text": "Общественное влияние",
		"footer-sitemap-text": "Карта сайта",
		"footer-system-status-text": "Состояние системы",
		"footer-product-help-text": "Справка по продуктам",
		"footer-legal-text": "Юридическая служба",
		"footer-favorite-things-text": "Избранные сервисы",
		"footer-zendesk-enterprise-text": "Zendesk для предприятий",
		"footer-zendesk-small-business-text": "Zendesk для малого бизнеса",
		"footer-zendesk-startups-text": "Zendesk для стартапов",
		"footer-zendesk-benchmark-text": "Сравнительный тест Zendesk",
		"footer-crm-text": "Gartner CRM Magic Quadrant",
		"footer-subscribe-header-text": "Присоединяйтесь к сообществу единомышленников",
		"footer-subscribe-additional-text": "Подписывайтесь на нашу новостную рассылку.",
		"footer-subscribe-label": "Подписаться",
		"footer-tou-text": "Условия использования",
		"footer-privacy-text": "Политика безопасности",
		"footer-cookie-text": "Политика в отношении Cookie",
		"copyright-info-text": "Gartner, Критические возможности центра взаимодействия с клиентами CRM, 8 июня 2020 г., Надин ЛеБлан, Брайан Манусама",
		"copyright-description-text": "Gartner не поддерживает каких-либо поставщиков, продукты или услуги, описанные в ее исследовательских публикациях, и не советует пользователям технологий выбирать только тех поставщиков, которые имеют самые высокие рейтинги или другие обозначения. Публикации исследований Gartner представляют собой мнения исследовательской и консультативной организации Gartner и не должны рассматриваться как констатация фактов. Gartner отказывается от всех гарантий, явных или подразумеваемых, в отношении данного исследования, включая любые гарантии коммерческой ценности или пригодности для конкретной цели. GARTNER является зарегистрированным товарным знаком и знаком обслуживания компании Gartner, Inc. и/или ее дочерних компаний в США и за рубежом и используется здесь с разрешения. Все права защищены.",
		"category-software": "ПО",
		"category-support": "Поддержка",
		"category-cx": "Обслуживание клиентов",
		"request-demo-select-product-error": "Выберите хотя бы один продукт",
		"request-demo-name-empty-error": "Введите имя контактного лица",
		"request-demo-name-too-short-error": "Имя должно быть не меньше",
		"request-demo-name-invalid-error": "Имя должно быть действительным именем, начинающимся с заглавной буквы",
		"error-characters": "символов",
		"request-demo-email-empty-error": "Введите email контактного лица",
		"request-demo-email-invalid": "Введённое значение должно быть действительным email-адресом",
		"request-demo-date-empty-error": "Выберите подходящую дату для демо",
		"request-demo-date-out-of-range-error": "Выберите любую подходящую дату с завтра до конца года",
		"request-demo-time-empty-error": "Выберите подходящее время для демо",
		"request-demo-time-out-of-range-error": "Выберите подходящее время с",
		"request-demo-time-error-preposition": "до",
		"sign-in-credentials-error": "Неверное имя пользователя или пароль",
		"sign-up-password-compromised-error": "Пароль скомпрометирован",
		"sign-up-password-confirmation-error": "Пароли должны совпадать",
		"sign-up-nickname-taken-error": "Этот никнейм уже используется",
		"sign-up-phone-empty-error": "Номер телефона обязателен",
		"sign-up-phone-invalid-error": "Введённое значение должно быть числовым",
		"sign-up-phone-too-short-error": "Номер телефона должен быть длиной",
		"sign-up-phone-too-short-error-suffix": "символов; Вы ввели",
		"sign-up-email-empty-error": "Email обязателен",
		"sign-up-dob-empty-error": "Дата рождения обязательна",
		"sign-up-dob-range-overflow-error": "Пользователь должен быть в возрасте",
		"sign-up-dob-range-overflow-error-suffix": "лет или старше",
		"sign-up-first-name-empty-error": "Имя обязательно",
		"sign-up-first-name-too-short-error": "Имя должно быть не меньше",
		"sign-up-first-name-invalid-error": "Имя должно быть действительным именем, начинающимся с заглавной буквы",
		"sign-up-last-name-empty-error": "Фамилия обязательна",
		"sign-up-last-name-too-short-error": "Имя должно быть не меньше",
		"sign-up-last-name-invalid-error": "Фамилия должна быть действительной фамилией, начинающейся с заглавной буквы",
		"sign-up-patronymic-too-short-error": "Отчество должно быть не меньше",
		"sign-up-patronymic-invalid-error": "Отчество должно быть действительным отчеством, начинающимся с заглавной буквы",
		"sign-up-password-empty-error": "Пароль обязателен",
		"sign-up-password-too-short-error": "Пароль должен быть не меньше",
		"sign-up-password-too-long-error": "Пароль должен быть не больше",
		"sign-up-password-weak-error": "Пароль должен содержать хотя бы одну заглавную букву, одну строчную букву, одну цифру и один специальный символ",
		"sign-up-nickname-too-short-error": "Никнейм должен быть не меньше",
		"sign-up-nickname-empty-error": "Никнейм обязателен",
		"sign-up-tos-missing-error": "Вы должны согласиться с Условиями использования, чтобы продолжить",
		"sign-in-username-empty-error": "Email или никнейм обязателен",
		"footer-subscribe-email-placeholder": "Какой у вас email?"
	}
};

function translate(locale, key) {
	return i18nMapping[locale][key];
}